<template>
    <div class="terms-page">
        <pictured-title add-class="title">
            <h1>Terms</h1>
        </pictured-title>
        <div class="content container-md">
            <b-tabs pills>
                <b-tab>
                    <template v-slot:title>
                        <span class="title-content">
                            Key terms
                        </span>
                    </template>
                    <p>IMPORTANT NOTICE: THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER. IT AFFECTS YOUR LEGAL RIGHTS AS DETAILED IN THE ARBITRATION AND CLASS ACTION WAIVER SECTION BELOW. PLEASE READ CAREFULLY.</p>
                    <p>ACCEPTANCE OF THESE TERMS BY DOWNLOADING THE GIG WIRE APP OR BY ACCESSING, VIEWING, OR USING THE APP, OR ANY TOOLS AND SERVICES PROVIDED IN CONNECTION WITH THE APP OR THE SITES (COLLECTIVELY THE APP, THE SITES, AND ALL RELATED TOOLS AND SERVICES) ARE REFERRED TO AS THE PLATFORM. YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS CONTAINED IN THESE TERMS OF USE.</p>
                    <p>IF YOU OBJECT TO ANYTHING IN THESE TERMS OF USE, INCLUDING THE MANDATORY ARBITRATION PROVISION AND CLASS ACTION WAIVER IN SECTION 33, OR OTHERWISE DO NOT UNDERSTAND OR AGREE TO BE BOUND BY THESE TERMS OF USE, DO NOT USE THE SERVICE AND UNINSTALL THE APP IMMEDIATELY.</p>
                    <p>These terms and conditions and end user license agreement (collectively “Terms of Use”) set forth the terms and conditions of Gig Wire, LLC. (“Gig Wire”) applicable to your use of the Service. Gig Wire encourages you to read these Terms of Use carefully.</p>
                    <p>All references to “you” or “your,” as applicable herein in context with the Terms, mean the person, company, entity or organization which accesses or uses the Service, in any manner, and each of your heirs, assigns, and successors. If you use the Platform on behalf of an entity, you represent and warrant that you have the authority to bind that entity, your acceptance of the Terms will be deemed an acceptance by that entity, and “you and “your” herein shall refer to that entity.</p>
                    <h4>KEY TERMS</h4>
                    <p>“Gig Wire” means and includes Gig Wire and its affiliates and subsidiaries and its investors, officers, directors, employees, agents, representatives, and assigns. Platform means all Gig Wire digital websites, digital smartphone applications, internal communications App, software, or other processes that facilitate the provision of Services by Service Partners who offer to provide Services or use the Platform, or Customers requesting Services from Service Partners or otherwise use the Platform.</p>
                    <p>“User” means any person, company, entity or organization who accesses or uses the Platform, including parents and caregivers, whether or not such User personally installed the Service Partner, the Customer or both of the Apps or created an account.</p>
                    <p>“Service Partner” means any User who offers to provide Services or otherwise uses the Platform to provide, receive payment for or facilitate the provision of Services.</p>
                    <p>“Customer” means any User requesting Services from Service Partners or otherwise uses the Platform to receive, pay for or facilitate the acquisition of Services.</p>
                    <p>“Content” means texts, chat messaging, or calls through Gig Wire’s internal communications App, graphics, images, music, software, audio, video, information or other materials, including but not limited to profile information, Service requests, Service offers, message threads, reviews, scheduling and calendar information, and other information or materials available on or through the Platform.</p>
                    <p>“Gig Wire Content” means all Content Gig Wire makes available on or through the Platform, including any Content licensed from a third party, but excluding User Content.</p>
                    <p>“User Content” means all Content you submit, post, upload, publish, or transmit on or through the Platform, including but not limited to chat messaging or calls through Gig Wire’s internal communications App, photographs, profile information, descriptions, postings, and reviews.</p>
                    <p>“Collective Content” means both User Content and Gig Wire Content. “Services” means all Services listed, scheduled, offered or provided by Service Partners, or sought, scheduled or received by Customers through the Platform.</p>

                </b-tab>
                <b-tab title="Second">
                    <template v-slot:title>
                        <span class="title-content">
                            Modifications
                        </span>
                    </template>
                    <h4>MODIFICATIONS</h4>
                    <p>“Gig Wire” means and includes Gig Wire and its affiliates and subsidiaries and its investors, officers, directors, employees, agents, representatives, and assigns. Platform means all Gig Wire digital websites, digital smartphone applications, internal communications App, software, or other processes that facilitate the provision of Services by Service Partners who offer to provide Services or use the Platform, or Customers requesting Services from Service Partners or otherwise use the Platform. “User” means any person, company, entity or organization who accesses or uses the Platform, including parents and caregivers, whether or not such User personally installed the Service Partner, the Customer or both of the Apps or created an account. “Service Partner” means any User who offers to provide Services or otherwise uses the Platform to provide, receive payment for or facilitate the provision of Services. “Customer” means any User requesting Services from Service Partners or otherwise uses the Platform to receive, pay for or facilitate the acquisition of Services. “Content” means texts, chat messaging, or calls through Gig Wire’s internal communications App, graphics, images, music, software, audio, video, information or other materials, including but not limited to profile information, Service requests, Service offers, message threads, reviews, scheduling and calendar information, and other information or materials available on or through the Platform. “Gig Wire Content” means all Content Gig Wire makes available on or through the Platform, including any Content licensed from a third party, but excluding User Content. “User Content” means all Content you submit, post, upload, publish, or transmit on or through the Platform, including but not limited to chat messaging or calls through Gig Wire’s internal communications App, photographs, profile information, descriptions, postings, and reviews. “Collective Content” means both User Content and Gig Wire Content. “Services” means all Services listed, scheduled, offered or provided by Service Partners, or sought, scheduled or received by Customers through the Platform.</p>

                </b-tab>
                <b-tab title="Third">
                    <template v-slot:title>
                        <span class="title-content">
                            Additional Terms<br> and Conditions
                        </span>
                    </template>
                    <h4>Additional Terms and Conditions</h4>
                    <p>“Gig Wire” means and includes Gig Wire and its affiliates and subsidiaries and its investors, officers, directors, employees, agents, representatives, and assigns. Platform means all Gig Wire digital websites, digital smartphone applications, internal communications App, software, or other processes that facilitate the provision of Services by Service Partners who offer to provide Services or use the Platform, or Customers requesting Services from Service Partners or otherwise use the Platform. “User” means any person, company, entity or organization who accesses or uses the Platform, including parents and caregivers, whether or not such User personally installed the Service Partner, the Customer or both of the Apps or created an account. “Service Partner” means any User who offers to provide Services or otherwise uses the Platform to provide, receive payment for or facilitate the provision of Services. “Customer” means any User requesting Services from Service Partners or otherwise uses the Platform to receive, pay for or facilitate the acquisition of Services. “Content” means texts, chat messaging, or calls through Gig Wire’s internal communications App, graphics, images, music, software, audio, video, information or other materials, including but not limited to profile information, Service requests, Service offers, message threads, reviews, scheduling and calendar information, and other information or materials available on or through the Platform. “Gig Wire Content” means all Content Gig Wire makes available on or through the Platform, including any Content licensed from a third party, but excluding User Content. “User Content” means all Content you submit, post, upload, publish, or transmit on or through the Platform, including but not limited to chat messaging or calls through Gig Wire’s internal communications App, photographs, profile information, descriptions, postings, and reviews. “Collective Content” means both User Content and Gig Wire Content. “Services” means all Services listed, scheduled, offered or provided by Service Partners, or sought, scheduled or received by Customers through the Platform.</p>
                    <ul>
                        <li>Privacy Policy. Please refer to the Gig Wire Privacy Policy at Gig Wire.com/privacy for information on how Gig Wire collects, uses and discloses information about you. </li>
                        <li>License. Subject to the terms and conditions set forth in these Terms of Use, Gig Wire grants you a personal, nonexclusive, nontransferable license to use the Platform and to download and use the App on any mobile device that you own or control, solely for your personal, non-commercial use except as expressly set forth herein.</li>
                    </ul>
                    <p>The Platform will be in the form and format as determined by Gig Wire in its sole discretion from time to time, and such form and format may limit or restrict use to certain types of devices at the exclusion of others and may have additional licensing terms restricting their use thereto.</p>
                    <p>Such license is subject to these Terms of Use and, except as expressly provided in these Terms of Use, does not include: (A) any resale or commercial use (except as expressly set forth herein) of the Service or of any content or materials contained therein (“Gig Wire Content”); (B) modifying or otherwise making any derivative uses of the Service or any Gig Wire Content; (C) use of any data mining, robots or similar data gathering or extraction methods; (D) reproducing, distributing, publicly performing or publicly displaying the Platform or the Gig Wire Content; (E) reverse engineering or otherwise attempting to discover any source code; or (F) any use of the Service other than for its intended purpose. Any use of the Platform or the Gig Wire Content other than as specifically authorized herein, without the prior, written permission of Gig Wire, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws, including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.</p>
                    <ul>
                        <li>
                            The Platform will be in the form and format as determined by Gig Wire in its sole discretion from time to time, and such form and format may limit or restrict use to certain types of devices at the exclusion of others and may have additional licensing terms restricting their use thereto. Such license is subject to these Terms of Use and, except as expressly provided in these Terms of Use, does not include: (A) any resale or commercial use (except as expressly set forth herein) of the Service or of any content or materials contained therein (“Gig Wire Content”); (B) modifying or otherwise making any derivative uses of the Service or any Gig Wire Content; (C) use of any data mining, robots or similar data gathering or extraction methods; (D) reproducing, distributing, publicly performing or publicly displaying the Platform or the Gig Wire Content; (E) reverse engineering or otherwise attempting to discover any source code; or (F) any use of the Service other than for its intended purpose. Any use of the Platform or the Gig Wire Content other than as specifically authorized herein, without the prior, written permission of Gig Wire, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws, including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.
                        </li>
                    </ul>
                    <p>You also consent to Gig Wire communicating with you about the Platform or in connection with the features, functions, and activities contained therein by SMS, text message, email or other electronic means. Your carrier’s normal messaging, data and other rates and fees will apply to these communications. The provision and delivery of text messages by Gig Wire or our text message service providers is governed by our SMS Terms and Conditions, which are expressly incorporated herein.</p>
                    <ul>

                        <li>Different terms and conditions. Certain areas of and/or products on the Platform may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions or policies. If there is a conflict between these Terms and terms and conditions or policies posted for a specific area or product, the latter take precedence with respect to your use of that area or product.</li>
                        <li>The Service Offers a Venue. The Platform merely offers tools, resources, and a venue to connect those seeking Services (Customers) with those seeking to provide Services (Service Partners). You understand and agree that Gig Wire: (A) does not employ, recommend or endorse any Users and has no control over the acts or omissions of any Users; (B) is not responsible or liable in any manner for the performance or conduct of any Users or other third parties online or offline; (C) makes no representations or warranties about the quality of the Services provided by any User or about your interactions or dealings with other Users; and (D) does not screen Users or automatically conduct any kind of identity or background checks except as otherwise expressly stated in these Terms of Use or on the Platform. Regardless of whether Gig Wire screens users or performs a background check, you should exercise caution and perform your own screening before connecting with anyone through the Platform, meeting anyone, engaging Users or accepting engagements. Gig Wire hereby expressly disclaims, and you hereby expressly release Gig Wire from, any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm and/or damages arising from and/or in any way related to the Platform or your interactions or dealings with other Users, including without limitation any acts and/or omissions of Users online or offline. By using the Platform, you acknowledge and agree that you are solely responsible for your use of the Platform and the connections you make and that ALL USE OF THE PLATFORM IS AT YOUR SOLE AND EXCLUSIVE RISK.</li>
                        <li>Transactions Are Between Users; Release. The Platform may be used to help obtain or offer Services provided by Users and to facilitate payment for such Services. However, Users transact solely between themselves, and Gig Wire is not a party to any transactions between Users. Gig Wire hereby expressly disclaims, and you hereby expressly release Gig Wire from, any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm and/or damages arising from and/or in any way related to disputes, dealings, or interactions between you and any other Users or third parties.</li>
                        <li>Eligibility. You represent and warrant that you currently meet and will continue to meet the following eligibility conditions (“Eligibility Conditions”) for as long as you use the Platform: (A) you are at least eighteen (18) years old; if you are under 18 years old, you have parental or guardian consent to use the Platform; if you are under 18 years old, and you are a volunteer for charities, or performing service hours for your school, or other agency or entity, you have parental or guardian consent; (B) you comply with all laws, rules and regulations in connection with your use of the Platform and any Services arranged through the Platform, including without limitation legal authorization to work in the jurisdiction in which you seek to provide or receive Services; (C) you have the right, authority and capacity to enter into these Terms of Use and to abide by all of the terms and conditions in these Terms of Use. By using the Platform, you understand and agree that Gig Wire may rely on the above Eligibility Conditions representations and warranties as true. You understand and agree that Gig Wire may revise the Eligibility Conditions from time to time and require new conditions and certifications. You understand that you will abide by such revised Eligibility Conditions or discontinue using the Platform and uninstall the App and you must discontinue use of the Platform if at any time you no longer meet the Eligibility Conditions. If Gig Wire becomes aware of or believes that there are violations of the Eligibility Conditions by any User or that the User has otherwise provided any false or misleading information, it may, among other things, suspend and/or terminate such User with or without notice at its sole discretion. If your account is terminated or suspended, you agree to make no further use of the Platform after termination or during the suspension.</li>

                    </ul>
                    <p>You understand and agree that Gig Wire does not routinely verify that any or all of the Eligibility Conditions are met by any other Users and you further understand and agree that Gig Wire is not responsible for assuring that the Eligibility Conditions are met or for any failure to suspend, terminate or prevent the use of the Platform by Users who do not meet the Eligibility Conditions. Except where expressly stated otherwise in these Terms of Use or on the Platform, you understand and agree that you are solely responsible for conducting any appropriate background checks and obtaining references prior to engaging another User to perform Services. You further understand and agree that you are solely responsible for making your own evaluations, decisions and assessments about whether to engage other Users to perform Services, accepting any engagements offered by other Users or otherwise interacting with other Users. Gig Wire hereby expressly disclaims, and you hereby expressly release Gig Wire from any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm or damages arising from or in any way related to: (a) any inaccuracy, untimeliness or incompleteness of a User’s Eligibility Conditions; and/or (b) any misstatements or misrepresentations made by any Users.</p>
                    <p>Although Gig Wire has no obligation to verify the Eligibility Conditions or conduct any other screenings, verifications or background checks, it reserves the right to do so in its sole discretion, and you hereby authorize Gig Wire to verify any or all of the above representations and warranties you make or the other information you provide. Such verification may include, without limitation, conducting criminal background checks, sex offender registry checks, motor vehicle records checks, identification verifications, credit checks and/or using available public records. You consent to any collection, use or disclosure in order to accomplish such verification. You agree that Gig Wire may take such action as it deems appropriate in its sole discretion, including without limitation suspending and/or terminating your account, should it determine, in its sole discretion, that you have violated any representation or warranty or any other provision of these Terms of Use or it otherwise determines in its sole discretion that such suspension or termination is appropriate for any reason. You acknowledge that you have no right to rely on any screenings, verifications, or other background checks undertaken from time to time by Gig Wire. In the event of any suspension or termination, you agree to make no further use of the Platform after termination or during the suspension.</p>
                    <ul>
                        <li>Service Partner Representations and Warranties. By registering or using the Platform to offer, post or provide Services, Service Partners represent and warrant that they, and the employees, agents, contractors, and subcontractors who may perform work for them, are properly and fully qualified and experienced, and licensed, certified, bonded, and insured, as required by applicable laws or regulations to which they may be subject in the jurisdiction(s) in which they offer their Services and in relation to the specific job they are performing.</li>
                    </ul>
                    <p>Service Partners further represent and warrant that: they have exclusive control over the details of the Services to be performed; the occupational skills, if any, required to perform the Services; the duration of time required to complete the performance of the Services to be provided; the tools, equipment and materials required to perform the Services to be provided and the amount of payment they require to perform the Services to be provided.</p>
                    <p>Service Partners offering Services further represent and warrant that they are independent contractors, and no agency, partnership, joint venture, or employment relationship is created as a result of the Terms of this Agreement, or the use of the Platform to provide Services to Users. Gig Wire and Service Partners acknowledge that one does not direct or control in any way the day-to-day activities of the other, or create or assume any obligation on behalf of the other.</p>
                    <p>Service Partners will take no position with respect to or on any tax return or application for benefits, or in any proceeding directly or indirectly involving Gig Wire that is inconsistent with you being an independent contractor and not an employee of Gig Wire.</p>
                    <p>Service Partners are not the employees or agent of Gig Wire and you are not authorized, and must not represent to any third party that you are authorized to make any commitment or otherwise act on behalf of Gig Wire.</p>
                    <p>As independent contractors, Service Partners are solely responsible for determining which requests for Services from Customers they choose to accept and how, when and where they will provide the requested Services.</p>
                    <p>Service Partners are not entitled to or eligible for any benefits that Gig Wire, its parents, subsidiaries, affiliates or other related entities may make available to its own employees.</p>
                    <p>Because Service Partners are independent contractors, Gig Wire will not withhold or make payments for Social Security, make unemployment insurance or disability insurance contributions, or obtain Service Partners Compensation insurance on Service Partners behalf. If, notwithstanding the foregoing, you are reclassified as an employee of Gig Wire, which Gig Wire denies, or any affiliate of Gig Wire, which Gig Wire denies, by the United States Internal Revenue Services (“IRS”), the US Department of Labor (“DOL”) or by any other federal, state or local agency, you agree that you will not, as result of such reclassification, be entitled to or eligible for, on either a prospective or retrospective basis, any employee benefits under any plans or programs established or maintained by either Gig Wire in any of its parents, subsidiaries, affiliates or related entities.</p>
                    <p>Users are solely responsible for filing all tax returns and submitting all payments as required by any federal, state, or local tax authority arising from the payment to Service Partners for Services performed for Customers.</p>
                    <p>Users will comply with all applicable federal, state, local and foreign laws governing self-employed individuals, where applicable, including laws requiring the payment of taxes, such as income and employment taxes, and Social Security, disability and other contributions. You agree to indemnify Gig Wire for the cost of any tax liabilities incurred by Gig Wire as a result of your failure to pay all applicable taxes in a timely manner.</p>
                    <ul>
                        <li>Verified Service Partners. A Customer may post the availability of a Gig as requiring a verified background check. Gig Wire partners with Checkr, a third-party company that performs services associated with background checks and screenings. Gig Wire hereby expressly disclaims, and you hereby expressly release, Gig Wire from any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm, or damages arising from, or in any way related to, your request to have a background check obtained through Gig Wire’s third-party background check service provider (Checkr). This includes, but is not limited to, any inaccuracy, untimeliness, or incompleteness of such a background check, or any misstatements or misrepresentations made therein. Services available from Checkr include, but are not limited to, the following: SSN Trace, Address History, National Criminal Records Check, County Criminal Records Check, Sex Offender Registry Check, Federal Criminal Records Check, Global Watchlist Records Check, State Criminal Records Check, County and Federal Civil Records Check, Driver Check, National and International Employment Verifications, Personal or Professional Reference Checks, National and International Education Verifications, Drug Screenings, Credit Checks.</li>
                        <li>Insurance. As an independent contractor, Service Partner is solely and exclusively responsible for Service Partner’s own insurance. Specifically, in the event that Service Partner is injured while working in the course and scope of an engagement sourced through Gig Wire, Service Partner acknowledges and understands that Service Partner will not be covered by any Service Partners compensation insurance coverage that Gig Wire may provide to its employees. Further, in the event that Service Partner’s actions cause an injury to a third party while Service Partner is working in the course and scope of performing an engagement sourced through Gig Wire, Service Partner acknowledges and understands that Service Partner will not be covered by any general liability or automobile liability insurance coverage that Gig Wire may have, and that Gig Wire is not making any commitment to defend and/or indemnify Service Partner in such circumstances, and specifically denies such obligation.</li>
                    </ul>
                    AllGig Wire Service Partnersmust have occupational accident insurance coverage in order to perform gig engagements. Gig Wire has arranged to have occupational insurance coverage available through On-Demand Independent Contractors Association (“ODICA”). Service Partners must obtain occupational accident insurance from ODICA’s insurance carrier, OneBeacon Accident & Health (“OneBeacon”). You will be charged a work safety fee for the occupational accident insurance, and you agree to pay that work safety fee. Additionally, you will be required to become a member of ODICA. Further information about ODICA and OneBeacon Accident and Health will be available on the website and in the Gig Wire App from time to time. You understand and agree that the work safety fee related to the provision of occupational health insurance is owed by you and will be deducted from the proceeds you earn for each gig engagement worked. By accessing and using the Platform, you consent and agree to these terms and agree to enroll as a member of ODICA. You also agree to abide by the Bylaws of ODICA, as amended from time to time.
                    <ul>
                        <li>AllGig Wire Service Partnersmust have occupational accident insurance coverage in order to perform gig engagements. Gig Wire has arranged to have occupational insurance coverage available through On-Demand Independent Contractors Association (“ODICA”). Service Partners must obtain occupational accident insurance from ODICA’s insurance carrier, OneBeacon Accident & Health (“OneBeacon”). You will be charged a work safety fee for the occupational accident insurance, and you agree to pay that work safety fee. Additionally, you will be required to become a member of ODICA. Further information about ODICA and OneBeacon Accident and Health will be available on the website and in the Gig Wire App from time to time. You understand and agree that the work safety fee related to the provision of occupational health insurance is owed by you and will be deducted from the proceeds you earn for each gig engagement worked. By accessing and using the Platform, you consent and agree to these terms and agree to enroll as a member of ODICA. You also agree to abide by the Bylaws of ODICA, as amended from time to time.</li>
                    </ul>
                    By signing this form, you also understand that you are enrolling as a member of ODICA with no voting rights. You understand and certify to the best of your knowledge that all information you provide to ODICA is complete and truthful and you are at least 18 years of age. Membership in ODICA is effective the first day of the month in which you enroll as a member. You must continue your membership in ODICA to participate on the Platform and accept gig engagements.
                    <ul>
                        <li>Right to Use Name and Logo for Promotional Purposes. User hereby grants Gig Wire a license to use, publish, and display Users’ name and logo on Gig Wire’s website and other Gig Wire company materials for the purpose of indicating that User has installed the Gig Wire app with the intention of sourcing Service Partners. User also agrees to allow Gig Wire to publish a description of the User’s company alongside User’s name and logo. Gig Wire hereby grants User a license to use, publish, and display Gig Wire’s name and logo in any similar manner. At the express written request of User or Gig Wire, the other party shall cease using, publishing, and displaying the other party’s name and/or logo within fourteen (14) days of such request.</li>
                        <li>No Professional Advice; Information Only. Any information, materials, content and/or advice provided through the Platform, whether by Gig Wire, Users or third parties, including without limitation Gig Wire blogs, including without limitation at Gig Wire.com/blog (the “Blog”), the Gig Wire Facebook pages, including without limitation at www.Facebook.com/Gig Wire and are for informational purposes only. If you have specific concerns or a situation arises requiring professional advice, you should consult with an appropriately trained and qualified professional. Gig Wire hereby expressly disclaims, and you hereby expressly release Gig Wire from, any and all liability whatsoever for any controversies, claims, suits, injuries, losses, harms and/or damages arising from and/or in any way related to the information, materials and content provided through the Platform, including without limitation on the Blog, Facebook pages and Twitter account.</li>
                        <li>Account Registration and Other Submissions. A person, company, entity or organization may access the Platform without registering for an account. To access and participate in certain features of the Platform, you will need to create a password-protected account (“Account”). You may register for an Account using your existing Facebook or Google account and log-in credentials (your “Third Party Site Password”). You agree to provide accurate, current, and complete information during the registration or request submission process and at all other times when you use the Platform, and to update your information to keep it accurate, current, and complete. You are solely responsible for safeguarding your Gig Wire password and, if applicable, your Third Party Site Password. You are solely responsible for all activity that occurs on your Account, and you will notify Gig Wire immediately of any unauthorized use. Gig Wire is not liable for any losses by any party caused by unauthorized use of your Account. Notwithstanding the foregoing, you may be liable for the losses of Gig Wire or others due to such unauthorized use.</li>
                        <li>Your License to Use the Platform. Subject to your compliance with these Terms, Gig Wire grants you a limited, non-exclusive, revocable, nontransferable, and non-sublicensable license to reproduce and display Collective Content (excluding any software source code) solely and expressly for your personal and non-commercial use and only in connection with your access to and participation in the Platform. You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Platform or Collective Content, except as expressly permitted in these Terms. The Platform and Collective Content are provided to you AS IS. If you download or print a copy of Collective Content for personal use, you must retain all copyright and other proprietary notices contained therein. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Gig Wire or its licensors, except for the licenses and rights expressly granted in these Terms.</li>
                        <li>Use of the Platform. You agree to use the Platform responsibly, exercise appropriate due diligence as a User and at all times act in accordance with the Terms of Use set forth herein in a manner that is appropriate to the purpose of the Platform.</li>
                        <li>Violations of Eligibility Conditions. As noted above, if Gig Wire becomes aware of or believes that there are violations of the Eligibility Conditions by any User or that any User has otherwise provided false or misleading information, it may, among other things, suspend and/or terminate such User with or without notice at its sole discretion. In the event of any suspension or termination, you agree to make no further use of the Platform after termination or during the suspension….</li>
                    </ul>
                </b-tab>
            </b-tabs>
        </div>
        <site-footer/>
    </div>
</template>
<style scoped lang="scss" src="./Terms.scss"></style>

<script>
    import { default as SiteFooter } from '@/core/components/global/Footer'
    import { default as PicturedTitle} from '../components/PicturedTitle'

    export default {
        components: {
            'site-footer': SiteFooter,
            'pictured-title': PicturedTitle
        },
    }
</script>
