/* eslint-disable */
import './arrow_right'
import './build_trust'
import './caret'
import './checkmark'
import './close_icon'
import './facebook_footer'
import './instagram_footer'
import './linkedin_footer'
import './logo'
import './money'
import './more_work'
import './schedule_management'
import './white-circle-green-tick'
import './white-circle-red-cross'
